### PR TITLE
Backport Linker API

### PR DESCRIPTION
**Pull request by evacchi**
Backport the API in #9 against Chicory 0.0.12 so that it can be used without waiting for a new upstream release, while we finalize things for 1.0.0. This is exactly the same as #9, except I am using the old 0.0.12 APIs to instantiate modules.

### CODE REVIEW

**Comment by evacchi** [comment]
ough, there might be a bug 🤔 I'll create a reproducer if any

**Comment by evacchi** [comment]
uhmm, it might not be a bug, it's looking for an `extism:host/env.log_debug` which is not defined in `extism-runtime.wasm`

**Comment by bhelx** [comment]
> uhmm, it might not be a bug, it's looking for an extism:host/env.log_debug which is not defined in extism-runtime.wasm

when is the last time we updated the runtime.wasm? i can't recall if i setup a process for that.

**Comment by evacchi** [comment]
it was a little old but I realized the real culprit was that we never implemented a bunch of host functions (like log_* or config_{get,set} etc) 😬

**Comment by evacchi** [comment]
fixed with #11

**Comment by evacchi** [comment]
Let's merge this to unblock the demo at https://github.com/evacchi/xtp-kafka-demo
We can always revert.

**Pull request merged**
